version: '3.0'

services:
  web:
    image: 'nginx:latest'
    ports:
    - "8080:80"
    volumes:
    - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./:/var/www
    depends_on:
    - php

  php:
    build:
      context: ./docker/php/
    volumes:
    - ./:/var/www
    depends_on:
    - mongodb

  mongodb:
    image: mongo:latest
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - mongodb:/data/db
    command: mongod --smallfiles --logpath=/dev/null

volumes:
  mongodb:
